_target_: src.app.infer_spider_new.Inferer

defaults:
  - dataloader: spider
  - net: 2024-10-16_19-48-52
  - post_proc: default

exp_name: Clean_${now:%Y-%m-%d}_${now:%H-%M-%S}
exdir: ${paths.infer_exdir}
checkpoint_path: ${paths.infer_ckpt}/2024-10-16_19-48-52.pth ##/work/hpc/spine-segmentation/logs/train/runs/test_delete/semantic_old_version.ckpt
data_name: Spider


model_inferer:
  _target_: monai.inferers.sliding_window_inference
  _partial_: true
  roi_size:  [32, 256, 256]
  sw_batch_size: 1 ##batch size for sliding window inference
  overlap: 0.6 ##overlap for sliding window inference

device: cuda:0

metric: ${model.metric}

softmax: True
argmax: False
threshold: 0.6