_target_: src.models.spider_semantic_module.SpiderLitModule

defaults:
  - optimizer: adam
  - scheduler: warmup_cosine




# compile model for faster training with pytorch 2.0
compile: false

sw_batch_size: 4
roi_x: 32
roi_y: 288 #160
roi_z: 288
infer_overlap: 0.5

# For criterion and me_target_: src.models.spider_semantic_module.SpiderLitModule

defaults:
  - optimizer: adam
  - scheduler: warmup_cosine
  - criterion: dice_dtm_fake
  - net: iso_attn_unet

# compile model for faster training with pytorch 2.0
compile: false

sw_batch_size: ${data.batch_size}
roi: [32, 256, 256] 
infer_overlap: 0.5

# For criterion and metrics configuration
name: ["None", "Vertebrae", "Canal", "Disk"]
# Background is ignoredtrics configuration 
criterion:
  _target_: monai.losses.DiceLoss
  softmax: True
  weight: [1, 3, 2]

name: ["Vertebrae", "Spinal Canal", "Disk"]