_target_: src.models.components.losses.dicece.DistanceMapDiceCELoss
dice_dtm:
  _target_: src.models.components.losses.w_dice.DistanceMapDiceLoss
  include_background: True
  # Kernel properties
  spatial_weight:
    _target_: src.utils.weight.spatial.DistanceMap
    gradient_kernel: 3
    gradient_mode: cross
    gaussian_kernel_size: 11
    gaussian_delta: [0.5, 1.5, 1.5] # Definition of sensitive area
    dim: 3
    # Class properties
    num_classes: 4
    # Edge threshold
    border_threshold: 0.5
    
    # Weight properties
    smooth_threshold: 0.6
    spacing: [0.05, 0.02, 0.02] # Distance distribution
    global_weight: False
    magnitude: 0.3
    inverse: True
    inverse_background: True # Set to true when background contribute to your semantics.
    post_proc: null

  norm: False
  post_proc: null
  
  # Partially initialization for argument synchronization
  _partial_: True

softmax: ${model.softmax}
include_background: True
lambda_dice: 0.8
lambda_ce: 0.2
weight: 
  _target_: torch.Tensor
  data: [1., 1., 1.2, 1.5]

reduction: mean
batch: False 

