_target_: src.models.net.get_unet.get_isotropic_attn_unet
#src.models.net.unet_transformer
# src/models/components/get_unet
config:
  spacing: ${data.spacing}
  roi: ${model.roi}
  bottleneck: 2
  base_channel: 16

# Keep this to instantiate Module
func:
  _target_: hydra.utils.instantiate
  _partial_: True

# Network properties
net:
  spatial_dims: 3
  in_channels: 1
  out_channels: 4

  kernel_size: 3
  up_kernel_size: 3

  # Channels matching, will be altered
  channels: [16, 32, 64, 128, 256, 512]
  strides: [2, 2, 2, 2, 2]

  # Training properties
  dropout: 0.5

inv: True 